ersion: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:12'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 'npm install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
            name: 'Build Project'
            command: 'CI=false npm run build'
  deploy:
    docker:
      -image: 'circleci/node:12'
    steps:
      - run:
            name: 'Deploy to Firebase Hosting'
            command: './node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"'
workflows:
  ci-cd-workflow:
    jobs:
      -build-and-test
      -deploy:
        requires:
          -build-and-test
        filters:
          branches:
            only: master